language: ruby
rvm:
  - 1.9.3
script: bundle exec ruby test/all.rb
notifications:
  email:
    - dev@opinsys.fi
    - esa-matti@suuronen.org
  irc: "irc.freenode.org#opinsys"
branches:
  only:
    - master
