school:
  prefix: ou=Groups
  classes:
  - top
  - posixGroup
  - puavoSchool
  - sambaGroupMapping
  dn_attribute: puavoId
  attributes:
    name: displayName
puavo_ca:
  host: 10.246.131.154
  port: 3000