development:
  host: 10.246.114.41
  base: dc=edu,dc=kunta1,dc=fi
  # base: o=puavo
  bind_dn: uid=admin,o=puavo
  password: npq5Drx2c9dAt9Dw

test: &test
  host: 10.246.114.41
  base: dc=edu,dc=kunta1,dc=fei
#  base: o=puavo
  bind_dn: uid=admin,o=puavo
  password: npq5Drx2c9dAt9Dw

production:
  host: 127.0.0.1
  method: :tls
#  base: dc=production,dc=local,dc=net
  base: o=puavo
  bind_dn: cn=admin,dc=local,dc=net
  password: secret

cucumber:
  <<: *test