towns:
  - Alahärmä
  - Alajärvi
  - Alastaro
  - Alavieska
  - Alavus
  - Anttola
  - Artjärvi
  - Asikkala
  - Askainen
  - Askola
  - Aura
  - Akaa
  - Brändö
  - Dragsfjärd
  - Eckerö
  - Elimäki
  - Eno
  - Enonkoski
  - Enontekiö
  - Espoo
  - Eura
  - Eurajoki
  - Evijärvi
  - Finström
  - Forssa
  - Föglö
  - Geta
  - Haapajärvi
  - Haapavesi
  - Hailuoto
  - Halikko
  - Halsua
  - Hamina
  - Hammarland
  - Hankasalmi
  - Hanko
  - Harjavalta
  - Hartola
  - Hattula
  - Hauho
  - Haukipudas
  - Haukivuori
  - Hausjärvi
  - Heinola
  - Heinolan mlk
  - Heinävesi
  - Helsinki
  - Vantaa
  - Himanka
  - Hirvensalmi
  - Hollola
  - Honkajoki
  - Houtskari
  - Huittinen
  - Humppila
  - Hyrynsalmi
  - Hyvinkää
  - Hämeenkyrö
  - Hämeenlinna
  - Heinola
  - Ii
  - Iisalmi
  - Iitti
  - Ikaalinen
  - Ilmajoki
  - Ilomantsi
  - Inari
  - Inkoo
  - Iniö
  - Isojoki
  - Isokyrö
  - Imatra
  - Jaala
  - Jalasjärvi
  - Janakkala
  - Joensuu
  - Jokioinen
  - Jomala
  - Joroinen
  - Joutsa
  - Joutseno
  - Juankoski
  - Jurva
  - Juuka
  - Juupajoki
  - Juva
  - Jyväskylä
  - Jyväskylän mlk
  - Jämijärvi
  - Jämsä
  - Jämsänkoski
  - Jäppilä
  - Järvenpää
  - Ei kotikuntaa Suomessa
  - Tuntematon
  - Ulkomaat
  - Kaarina
  - Kaavi
  - Kajaani
  - Kalajoki
  - Kalanti
  - Kalvola
  - Kangasala
  - Kangaslampi
  - Kangasniemi
  - Kankaanpää
  - Kannonkoski
  - Kannus
  - Karijoki
  - Karinainen
  - Karjaa
  - Karjalohja
  - Karkkila
  - Karstula
  - Karttula
  - Karvia
  - Kaskinen
  - Kauhajoki
  - Kauhava
  - Kauniainen
  - Kaustinen
  - Keitele
  - Kemi
  - Keminmaa
  - Kemiö
  - Kempele
  - Kerava
  - Kerimäki
  - Kestilä
  - Kesälahti
  - Keuruu
  - Kihniö
  - Kiihtelysvaara
  - Kiikala
  - Kiikoinen
  - Kiiminki
  - Kinnula
  - Kirkkonummi
  - Kisko
  - Kitee
  - Kittilä
  - Kiukainen
  - Kiuruvesi
  - Kivijärvi
  - Kodisjoki
  - Kokemäki
  - Kokkola
  - Kolari
  - Konginkangas
  - Konnevesi
  - Kontiolahti
  - Korpilahti
  - Korppoo
  - Korsnäs
  - Kortesjärvi
  - Hämeenkoski
  - Koski Tl
  - Kotka
  - Kouvola
  - Kristiinankaupunki
  - Kruunupyy
  - Kuhmalahti
  - Kuhmo
  - Kuhmoinen
  - Kuivaniemi
  - Kullaa
  - Kumlinge
  - Kuopio
  - Kuorevesi
  - Kuortane
  - Kurikka
  - Kuru
  - Kustavi
  - Kuusamo
  - Kuusankoski
  - Kuusjoki
  - Outokumpu
  - Kylmäkoski
  - Kyyjärvi
  - Kälviä
  - Kärkölä
  - Kärsämäki
  - Kökar
  - Köyliö
  - Kemijärvi
  - Kemiönsaari
  - Lahti
  - Laihia
  - Laitila
  - Lammi
  - Lapinlahti
  - Lappajärvi
  - Lappeenranta
  - Lappi
  - Lapinjärvi
  - Lapua
  - Laukaa
  - Lavia
  - Lehtimäki
  - Leivonmäki
  - Lemi
  - Lemland
  - Lempäälä
  - Lemu
  - Leppävirta
  - Lestijärvi
  - Lieksa
  - Lieto
  - Liljendal
  - Liminka
  - Liperi
  - Lohja
  - Lohjan kunta
  - Lohtaja
  - Loimaa
  - Loimaan kunta
  - Loppi
  - Loviisa
  - Luhanka
  - Lumijoki
  - Lumparland
  - Luopioinen
  - Luoto
  - Luumäki
  - Luvia
  - Längelmäki
  - Lohja
  - Parainen
  - Maalahti
  - Maaninka
  - Maarianhamina
  - Maksamaa
  - Marttila
  - Masku
  - Mellilä
  - Merijärvi
  - Merikarvia
  - Merimasku
  - Miehikkälä
  - Mietoinen
  - Mikkeli
  - Mikkelin mlk
  - Mouhijärvi
  - Muhos
  - Multia
  - Muonio
  - Mustasaari
  - Muurame
  - Muurla
  - Mynämäki
  - Myrskylä
  - Mäntsälä
  - Mänttä
  - Mäntyharju
  - Mänttä-Vilppula
  - Naantali
  - Nakkila
  - Nastola
  - Nauvo
  - Nilsiä
  - Nivala
  - Nokia
  - Noormarkku
  - Nousiainen
  - Nummi-Pusula
  - Nurmes
  - Nurmijärvi
  - Nurmo
  - Närpiö
  - Oravainen
  - Orimattila
  - Oripää
  - Orivesi
  - Oulainen
  - Oulu
  - Oulunsalo
  - Parainen
  - Padasjoki
  - Paimio
  - Paltamo
  - Parikkala
  - Parkano
  - Pattijoki
  - Pelkosenniemi
  - Perho
  - Pernaja
  - Perniö
  - Pertteli
  - Pertunmaa
  - Peräseinäjoki
  - Petäjävesi
  - Pieksämäki
  - Pieksämäen mlk
  - Pielavesi
  - Pietarsaari
  - Pedersören kunta
  - Pihtipudas
  - Piikkiö
  - Piippola
  - Pirkkala
  - Pohja
  - Polvijärvi
  - Pomarkku
  - Pori
  - Pornainen
  - Porvoo
  - Porvoon mlk
  - Posio
  - Pudasjärvi
  - Pukkila
  - Pulkkila
  - Punkaharju
  - Punkalaidun
  - Puolanka
  - Puumala
  - Pyhtää
  - Pyhäjoki
  - Pyhäjärvi
  - Pyhäntä
  - Pyhäranta
  - Pyhäselkä
  - Pylkönmäki
  - Pälkäne
  - Pöytyä
  - Porvoo
  - Pieksänmaa
  - Raahe
  - Raisio
  - Rantasalmi
  - Rantsila
  - Ranua
  - Rauma
  - Rauman mlk
  - Rautalampi
  - Rautavaara
  - Rautjärvi
  - Reisjärvi
  - Renko
  - Riihimäki
  - Ristiina
  - Ristijärvi
  - Rovaniemi
  - Rovaniemen mlk
  - Ruokolahti
  - Ruotsinpyhtää
  - Ruovesi
  - Rusko
  - Rymättylä
  - Rääkkylä
  - Ruukki
  - Raasepori
  - Saari
  - Saarijärvi
  - Sahalahti
  - Salla
  - Salo
  - Saltvik
  - Sammatti
  - Sauvo
  - Savitaipale
  - Savonlinna
  - Savonranta
  - Savukoski
  - Seinäjoki
  - Sievi
  - Siikainen
  - Siikajoki
  - Siilinjärvi
  - Simo
  - Sipoo
  - Anjalankoski
  - Siuntio
  - Sodankylä
  - Soini
  - Somero
  - Sonkajärvi
  - Sotkamo
  - Sottunga
  - Sulkava
  - Sumiainen
  - Sund
  - Suodenniemi
  - Suolahti
  - Suomenniemi
  - Suomusjärvi
  - Suomussalmi
  - Suonenjoki
  - Sysmä
  - Säkylä
  - Särkisalo
  - Vaala
  - Säynätsalo
  - Sastamala
  - Siikalatva
  - Taipalsaari
  - Taivalkoski
  - Taivassalo
  - Tammela
  - Tammisaari
  - Tampere
  - Tarvasjoki
  - Temmes
  - Tenhola
  - Tervo
  - Tervola
  - Teuva
  - Tohmajärvi
  - Toholampi
  - Toivakka
  - Tornio
  - Turku
  - Pello
  - Tuulos
  - Tuupovaara
  - Tuusniemi
  - Tuusula
  - Tyrnävä
  - Töysä
  - Toijala
  - Ullava
  - Ulvila
  - Urjala
  - Utajärvi
  - Utsjoki
  - Uukuniemi
  - Uurainen
  - Uusikaarlepyy
  - Uusikaupunki
  - Vaasa
  - Vahto
  - Valkeakoski
  - Valkeala
  - Valtimo
  - Vammala
  - Vampula
  - Varkaus
  - Varpaisjärvi
  - Vehkalahti
  - Vehmaa
  - Vehmersalmi
  - Velkua
  - Vesanto
  - Vesilahti
  - Västanfjärd
  - Veteli
  - Vieremä
  - Vihanti
  - Vihti
  - Viiala
  - Viitasaari
  - Viljakkala
  - Vilppula
  - Vimpeli
  - Virolahti
  - Virrat
  - Virtasalmi
  - Vuolijoki
  - Vårdö
  - Vähäkyrö
  - Värtsilä
  - Vöyri
  - Vöyri-Maksamaa
  - Vöyri
  - Ylihärmä
  - Yli-Ii
  - Ylikiiminki
  - Ylistaro
  - Ylitornio
  - Ylivieska
  - Ylämaa
  - Yläne
  - Ylöjärvi
  - Ypäjä
  - Äetsä
  - Ähtäri
  - Äänekoski
